### PR TITLE
Use the Meson Build System

### PR DESCRIPTION
**Pull request by lolzballs**
The meson build system is used by sway/wlroots and many other Linux projects.

Some advantages over the `build.sh` script are:
- automatic cloning/compilation of cglm via subprojects (can be extended to physac/wlroots if wanted)
- incremental builds
- parallel builds

### CODE REVIEW

**Comment by nschweitz** [comment]
Fair enough. I had trouble making git merge correctly so I just copied the files into a new commit.

Thanks! It's merged, even if it doesn't say so here.

**Comment by nschweitz** [comment]
When the shaders are changed, meson only recompiles them and doesn't recompile the entire program, which it should since they are included in `renderer.c`. How can I fix that?

**Comment by lolzballs** [comment]
Are you sure about that? I believe the meson build files are setup correctly to handle this (see [here](https://mesonbuild.com/FAQ.html#how-do-i-tell-meson-that-my-sources-use-generated-headers)).

When I change postprocess.vert and then compile it seems like it builds stuff correctly (compiles the shader, re-compiles renderer.c, and then re-compiles vkwc):

```
$ ninja -C build -v 
ninja: Entering directory `build'
[1/3] /usr/bin/glslangValidator -V ../vulkan/shaders/postprocess.vert -o vulkan/shaders/postprocess.vert.h --vn postprocess_vert_data
../vulkan/shaders/postprocess.vert
[2/3] cc -Ivkwc.p -I. -I.. -I../subprojects/cglm/include -Ivulkan/shaders -I/usr/include/libdrm -I/usr/include/pixman-1 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -O0 -g -DWLR_USE_UNSTABLE -MD -MQ vkwc.p/vulkan_renderer.c.o -MF vkwc.p/vulkan_renderer.c.o.d -o vkwc.p/vulkan_renderer.c.o -c ../vulkan/renderer.c
[3/3] cc  -o vkwc vkwc.p/vkwc.c.o vkwc.p/vulkan_pixel_format.c.o vkwc.p/vulkan_renderer.c.o vkwc.p/vulkan_texture.c.o vkwc.p/vulkan_util.c.o vkwc.p/vulkan_vulkan.c.o vkwc.p/render.c.o vkwc.p/util.c.o vkwc.p/surface.c.o vkwc.p/misc_pixel_format.c.o -Wl,--as-needed -Wl,--no-undefined '-Wl,-rpath,$ORIGIN/subprojects/cglm' -Wl,-rpath-link,/home/bcheng/usr/code/vkwc/build/subprojects/cglm -Wl,--start-group libxdg_shell.a subprojects/cglm/libcglm.so.0.8.7 /usr/lib/libwlroots.so /usr/lib/libvulkan.so /usr/lib/libpixman-1.so /usr/lib/libxkbcommon.so -lm /usr/lib/libwayland-server.so -Wl,--end-group
```

**Comment by lolzballs** [comment]
Oh I see, in 05a3b00, you updated the includes to point to the build folder. I looks like that breaks the dependency resolution, and it would also force people to name their build folder "build". I pushed a new commit to this PR that should resolve the issue.

**Comment by nschweitz** [comment]
Turns out some files not tracked by git were somehow interfering with meson, prompting me to "fix" this in the commit you mentioned.

Thanks! It works now.

**Pull request merged**
